---
- hosts: all
  become: yes

  tasks:
    - name: Set hosts
      shell: sed -i -e '$ a 192.168.20.21 mongo-database' /etc/hosts
    
    - name: Open port
      shell: iptables -I INPUT -p tcp -s 192.168.20.23 --dport 8080 -j ACCEPT

    # - name: Block routing
    #   shell: iptables -P INPUT DROP

    - name: Java 11 - add repository
      apt_repository:
        repo: "ppa:openjdk-r/ppa"
        state: present
        update_cache: yes

    - name: Install java 11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: create directory
      file:
        path: /etc/top-streamers-backend
        recurse: yes
        state: directory

    - name: copy jar
      copy:
        src: ./top-streamers-backend/build/libs/top-streamers-0.0.1.jar
        dest: /etc/top-streamers-backend/top-streamers-0.0.1.jar
        mode: "0644"

    - name: copy database configuration
      copy:
        src: ./top-streamers-backend/application.properties-PROD
        dest: /etc/top-streamers-backend/application.properties
        mode: "0644"

    - name: Run jar
      shell: nohup java -jar /etc/top-streamers-backend/top-streamers-0.0.1.jar --spring.config.location=file:///etc/top-streamers-backend/application.properties &
