apiVersion: v1

kind: Service

metadata:
  name: backend-service
  labels:
    app: backend-service
    
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: backend-pod