apiVersion: v1

kind: Service

metadata:
  name: mongo-service
  labels:
    app: mongo-service
    
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30002
  selector:
    app: mongo-pod