apiVersion: apps/v1

kind: Deployment

metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod

  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-pod
    spec:
      containers:
        - name: frontend-container
          image: frontendvm
          imagePullPolicy: Never
          ports:
            - containerPort: 80 
              hostPort: 4200
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3